In [11]:
import torch

In [12]:
states = torch.rand([64,4])
actions = torch.rand([64,2])


In [16]:
state_actions = zip(states,actions)
for state, action in state_actions:
    print(state,action)


tensor([0.6332, 0.2981, 0.6393, 0.0940]) tensor([0.1801, 0.9133])
tensor([0.4273, 0.7472, 0.8391, 0.5196]) tensor([0.2089, 0.0416])
tensor([0.9097, 0.7542, 0.1573, 0.0228]) tensor([0.1296, 0.4592])
tensor([0.3418, 0.7036, 0.2467, 0.3849]) tensor([0.2412, 0.9891])
tensor([0.7923, 0.9218, 0.3438, 0.2205]) tensor([0.1678, 0.7302])
tensor([0.1401, 0.1589, 0.6148, 0.9650]) tensor([0.3391, 0.7860])
tensor([0.8172, 0.3737, 0.2593, 0.7387]) tensor([0.8918, 0.1069])
tensor([0.4123, 0.9705, 0.3279, 0.4869]) tensor([0.1936, 0.0969])
tensor([0.7010, 0.7427, 0.2400, 0.2704]) tensor([0.6798, 0.6424])
tensor([0.8058, 0.7849, 0.8243, 0.9726]) tensor([0.3080, 0.4015])
tensor([0.4484, 0.6943, 0.6937, 0.0446]) tensor([0.3708, 0.3215])
tensor([0.4732, 0.6267, 0.8737, 0.7555]) tensor([0.9423, 0.2922])
tensor([0.3518, 0.2537, 0.2279, 0.4083]) tensor([0.2311, 0.3998])
tensor([0.5157, 0.9660, 0.9120, 0.2508]) tensor([0.8732, 0.5835])
tensor([0.1686, 0.5447, 0.8667, 0.8873]) tensor([0.1134, 0.9724])
tensor([0.

Stacking the tensors didn't seem to work.
